### ISSUE TITLE
Adding extra phonons to dataset

### ISSUE THREAD

**Issue by Kozlan-TA** [ninarina12/phononDoS_tutorial#1]
Hello! I am trying to add new phonon data to dataset, but I don't understand how to normalize phononDOS like you. I downloaded phonon data from materials project (same structures), but using cutoff to 1000 cm^(-1) and minmax normalization makes results much weaker. Please, can you tell how you transformed phonon density of states for dataset?

**Comment by ninarina12** [comment]
Hi! We did some additional preprocessing to the phononDoS to downsample spectra down to 51 points, detailed here: https://onlinelibrary.wiley.com/action/downloadSupplement?doi=10.1002%2Fadvs.202004214&file=advs2492-sup-0001-SuppMat.pdf. The gist of it was to smooth the raw spectra using a Savitzky-Golay filter of window length 101 and
polynomial order 3, and then interpolate the smoothed spectra to 51 evenly-spaced points from 0-1000 cm^(-1). Representative examples of the before and after are shown in the linked pdf.

**Comment by Kozlan-TA** [comment]
Hello again, sorry for delay. I successfully made it. Thanks for explaining this to me!
